### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by Xenoamor** [vgm64/gmplot#116]
Has the maintainer @vgm64 ceased to maintain this project? It looks like he hasn't been active in over a year.
There seems to be a bunch of pull requests that would really benefit the codebase if they were merged.

If we don't hear from him his email is in setup.py that I'll give a try but failing that I guess we might want to look at moving to a new repo so this project can continue until his return

**Comment by vgm64** [comment]
I've been watching PRs stacking up and acknowledge I haven't been
administrating the repo successfully for quite a while. Another
maintainer(s) is certainly warranted.

**Comment by Xenoamor** [comment]
Thanks for the fast response!

If you can't find anyone let me know as I'd be happy to help although I don't have a huge amount of gmplot experience. Perhaps there are more active users lurking around here who might be open to the idea

**Comment by frslm** [comment]
I wouldn't mind helping out as well.

**Comment by vgm64** [comment]
Welcome @sandrotosi  and @frslm to direct access to the repo!

**Comment by sandrotosi** [comment]
thanks! and we just migrated the project to https://github.com/gmplot/gmplot
