### ISSUE TITLE
NameError: name 'latitudes' is not defined

### ISSUE THREAD

**Issue by mjbcncs** [vgm64/gmplot#27]
I installed the newest version of gmplot on my machine. but when I execute the sample code:
import gmplot

gmap = gmplot.GoogleMapPlotter(37.428, -122.145, 16)

gmap.plot(latitudes, longitudes, 'cornflowerblue', edge_width=10)
gmap.scatter(more_lats, more_lngs, '#3B0B39', size=40, marker=False)
gmap.scatter(marker_lats, marker_lngs, 'k', marker=True)
gmap.heatmap(heat_lats, heat_lngs)

gmap.draw("mymap.html")

It gave me the following error message.

NameError                                 Traceback (most recent call last)
<ipython-input-1-0f1e59eccdc3> in <module>()
      3 gmap = gmplot.GoogleMapPlotter(37.428, -122.145, 16)
      4 
----> 5 gmap.plot(latitudes, longitudes, 'cornflowerblue', edge_width=10)
      6 gmap.scatter(more_lats, more_lngs, '#3B0B39', size=40, marker=False)
      7 gmap.scatter(marker_lats, marker_lngs, 'k', marker=True)

NameError: name 'latitudes' is not defined

What is going on with my operation here?

**Comment by vgm64** [comment]
There are some dummy variables in the example code. Put some latitudes and
longitudes in 'latitudes'  and 'longitudes' variables, as well as the other
placeholder variable names and you should be good to go.

*gmap.plot(latitudes, longitudes, 'cornflowerblue', edge_width=10)*

Michael Woods

**Comment by mjbcncs** [comment]
Yes, thanks. I figured it out somehow.

**Comment by likui01** [comment]
gmap.plot(38.428, -122.145, 'cornflowerblue', edge_width=10)

  File "C:\Python27\lib\site-packages\gmplot\gmplot.py", line 119, in plot
    path = zip(lats, lngs)

TypeError: zip argument #1 must support iteration

im getting this error, any idea why?

**Comment by vgm64** [comment]
Yup. The first two args need to be lists or tuples. So [38.428]  for
example.

Michael Woods

**Comment by likui01** [comment]
Thank you so much

**Comment by likui01** [comment]
okay, one more question.
does it plot absolute coordinates or relative.
i gave it set of same coordinates in a list. it should have mark the same point multiple times. but it plot a route.
do you why?

**Comment by vgm64** [comment]
Should be absolute. What did the path look like?

Michael Woods

**Comment by likui01** [comment]
okay, i found the error.
is it possible to save it as a image, instead of html

**Comment by vgm64** [comment]
The map is generated by Google when the page loads so needs a browser. You
could screen capture?

Michael Woods
