### ISSUE TITLE
AttributeError: module 'gmplot' has no attribute 'GoogleMapPlotter'

### ISSUE THREAD

**Issue by LingzhouAo** [vgm64/gmplot#42]
How can I fix this problem? I just copied the test code to run

**Comment by share-with-me** [comment]
I face this issue too.

**Comment by vgm64** [comment]
The Readme should now be updated to show the correct syntax. If it doesn't
solve your problem, can you share the exact piece of code you're trying to
execute?

**Comment by brettvanderwerff** [comment]
I am pretty new to github and programming in general and hit on wall on this too. I think the gmplot directory could to be imported as a package as a workaround so where the readme starts as "import gmplot" I did "from gmplot import gmplot" then everything worked. There is probably a more correct solution and like I said, I am new.

**Comment by denson** [comment]
This is definitely not fixed. I installed and ran the unit test...got the error. Copy and pasted the readme code...got the error. Copied the contents of the gmplot directory into the script directory, got a new error: 

from gmplot import gmplot 
ImportError: cannot import name gmplot

**Comment by vgm64** [comment]
Ok, let's get this fixed. Can you share your exact commands, including
cloning and any cd'ing, to reproduce the error?

**Comment by denson** [comment]
An uninstall/reinstall of the package fixed the issue. :)
