### ISSUE TITLE
Should readme import statement say from "from gmplot import gmplot" instead of "import gmplot"

### ISSUE THREAD

**Issue by brettvanderwerff** [vgm64/gmplot#59]
Please note that I am very new to programming and sorry if I am missing something obvious but I could not get the crash course script in the readme to work until changing the import statement from "import gmplot" to "from gmplot imort gmplot" then everything worked for me.

**Comment by vgm64** [comment]
> sorry if I am missing something obvious

Nope. Fixed now.
