### ISSUE TITLE
Use of StringIO make module incompatible with Python 3

### ISSUE THREAD

**Issue by paololucchino** [vgm64/gmplot#66]
Hi @vgm64 ,

The [introduction of StringIO](https://github.com/vgm64/gmplot/blob/master/gmplot/gmplot.py#L6) makes the module not compatible with Python 3.
 
Raises: `ModuleNotFoundError: No module named 'StringIO'`, see more [here](https://stackoverflow.com/questions/11914472/stringio-in-python3).

I haven't encountered any other incompatibilities with python 3 apart from this one, so I wonder whether the feature implemented in [this recent commit](https://github.com/vgm64/gmplot/commit/ad6df42e96f9c3accefe691212af06376706f96e) is worth the generating an incompatibility. 

Perhaps there is an alternative way of implementing it?

**Comment by vgm64** [comment]
It isn't worth the incompatibility, you're right. I'll revert it and look
for solutions later.

**Comment by paololucchino** [comment]
Thanks @vgm64 .
Issue addressed in [this commit](https://github.com/vgm64/gmplot/commit/b8ef59fa75782a92855b22c62f469dc90ac1c2b5). Closing issue.
