### ISSUE TITLE
Incorrect relative import in most recent commit. Module import breaks.

### ISSUE THREAD

**Issue by paololucchino** [vgm64/gmplot#70]
Hi @vgm64 @OmriRoames, I think the latest commit may have a bug?

In [https://github.com/vgm64/gmplot/blob/master/gmplot/gmplot.py#L9]:
`color_dicts` should be `.color_dicts`.

This is the error message I get:

```----> 1 from .gmplot import GoogleMapPlotter

~/code/sonder/micro-neighborhoods/micro-neighborhoods-env/lib/python3.6/site-packages/gmplot/gmplot.py in <module>()
      7 from collections import namedtuple
      8 
----> 9 from color_dicts import mpl_color_map, html_color_codes
     10 from google_maps_templates import SYMBOLS, CIRCLE
     11 

ModuleNotFoundError: No module named 'color_dicts```

**Comment by vgm64** [comment]
Confirmed. Starting using future's absolute import in 8e6a886ca6fa54ce95f5334943288760fd0a7bf2. Problem should be fixed. Thanks for the report!
