### ISSUE TITLE
Better Text description

### ISSUE THREAD

**Issue by ichigo29** [vgm64/gmplot#71]
Hi, I'm actually trying gmplot for a study project. The idea is to plot on google map the evolution of mobile network in my city since 2014. To do so, I need to plot markers with a description but the option "title="smthg"" doesn't accept \n. Is their a way to do \n in markers description ?

**Comment by vgm64** [comment]
Does `<br>` instead of `\n` work?

**Comment by sandrotosi** [comment]
or you can use `<p>...</p>` as in https://github.com/sandrotosi/ingresstools/blob/master/tfl_bus_routes_first_stop.py#L24 resulting in http://sandrotosi.me/ingress/london/tfl_bus_routes_first_stop.html (click on any marker to see the popup menu)

**Comment by ichigo29** [comment]
the <br> doesn't work. The infowindows that you are using sandrotosi really interest me, but I don't known how you have manage to use them. Is there a page where I could learn how to use them. when I try a gmap.infowindow() it says that no objects has the attribute infowindow

**Comment by sandrotosi** [comment]
they are part of https://github.com/vgm64/gmplot/pull/15

**Comment by ichigo29** [comment]
Here is the code where I do tests : 

> import gmplot
>gmap = gmplot.GoogleMapPlotter(0, 0, 13)
>hidden_gem_lat, hidden_gem_lon = 0, 0
>gmap.marker(0,0,'cornflowerblue')
>content = "'test'"
>gmap.infowindow(content,0,0)
>gmap.draw("my_map.html")


And then here is the traceback I have : 

`Traceback (most recent call last):
  File "map.py", line 10, in <module>
    gmap.infowindow(content,0,0)
AttributeError: 'GoogleMapPlotter' object has no attribute 'infowindow'
`

**Comment by ichigo29** [comment]
Sory I'm beginner in programming and too with github.
I have to import something else to use infowindow with gmplot ?

**Comment by Bargey13** [comment]
I'm having the same problem and am trying to figure it out. I think you have all libraries you need in the #15 example. I think the content generated in the for loop.  But I'm not really sure either.

**Comment by ichigo29** [comment]
Ok, I've found how to implement infowindows in gmplot. Thanks for the help.
For the ones how are searching, sandrotosi commit a modification of gmplot on his git, [link here](https://github.com/sandrotosi/gmplot/blob/master/gmplot/gmplot.py) .
All you have to do is replace the gmplot.py you downloaded with pip by the one linked. mine was on "/home/pierre/.local/lib/python2.7/site-packages"
