### ISSUE TITLE
For Development purposes only

### ISSUE THREAD

**Issue by danybenjamin-tc** [vgm64/gmplot#79]
My maps won't generate anymore. It displays a greyed out watermark that says 'For Development purposes only'

**Comment by vgm64** [comment]
Are you using an Api key? Can you share code to reproduce?

**Comment by danybenjamin-tc** [comment]
I am now, I wasn't before. It works now!

**Comment by danybenjamin-tc** [comment]
Yes. Looks that way. So all you have to do is add:
`gmap = gmplot.GoogleMapPlotter....
gmap.apikey = 'XXXXXXXXXXXXXXXXXXX`

**Comment by vgm64** [comment]
The init accepts it as an arg, too.

**Comment by ancago** [comment]
but I can only get an apikey when I pay in Google Cloud Platform for access to maps, right?

**Comment by vgm64** [comment]
Getting an api key should be free and for small scale usage (especially personal usage) it should remain free. Honestly, I haven't looked into the changes myself yet!

https://mapsplatformtransition.withgoogle.com/calculator

**Comment by ancago** [comment]
ok I got it! I added in gmap = gmplot.GoogleMapPlotter() as a next argument (apikey='..'), I also tried to add it separately as gmap.apikey = '...' but in both cases I see a map for a second and then it disappears and I get this: 
Oops! Something went wrong.
This page didn't load Google Maps correctly. See the JavaScript console for technical details... 
any idea of how can I fix this?

**Comment by WilliamSNorth** [comment]
> Yes. Looks that way. So all you have to do is add:
> `gmap = gmplot.GoogleMapPlotter.... gmap.apikey = 'XXXXXXXXXXXXXXXXXXX`

I'm also having some issues adding the API key. 
I tried 
gmap = gmplot.GoogleMapPlotter
gmap.apikey = "inserting API key here"

However I still have the development purposes only issue, any ideas?

**Comment by averysmith10** [comment]
I'm also getting the issue...

**Comment by tylerclover** [comment]
I was having a similar problem, but it turns out I just had to enable billing on Google Cloud. If you check the developer console in your browser when you pull up the map, you might see an error about this. @Billy-North @averysmith10
