### ISSUE TITLE
GoogleMapPlotter no longer accepts API Keys as arguments

### ISSUE THREAD

**Issue by scottishbee** [vgm64/gmplot#94]
Just this morning I spun up some new code for mapping and received a new-to-me issue: GoogleMapPlotter won't accept the fifth argument for the Google Maps API Key.

```
import gmplot
gmplot.GoogleMapPlotter(37.766956, -122.438481, 13, api_key)
```

This same code works in a script I have running from a few days ago, but in my new script it returns the error:

> __init__() takes 4 positional arguments but 5 were given

**Comment by WilliamSNorth** [comment]
Did you end up fixing the issue, I having some issues adding the API key to gmplot?

**Comment by scottishbee** [comment]
I'm not sure what I did, but it now works.  I suspect I just removed and then reinstalled gmplot.
