### ISSUE TITLE
info bubbles?

### ISSUE THREAD

**Issue by sstephans** [vgm64/gmplot#96]
Is it possible to include information bubbles, possibly linking to pictures or pages, for each marker? I have a long list of markers to iterate through and that works for populating the latitude and longitude lists, but I want each marker to have information associated with it that will appear upon clicking, like how google maps does it, if possible. 

Sorry for noob question. I'm still trying to learn your repo, not sure if I'm missing something or if it's just not possible. 

Thanks!

**Comment by sandrotosi** [comment]
like the InfoWindows? i've implemented them a while ago with https://github.com/vgm64/gmplot/pull/15

**Comment by sstephans** [comment]
Possibly? If I'm reading that correctly I can put html in the string named contents and when you click on a marker, the contents of contents will be shown?

**Comment by sandrotosi** [comment]
i used that feature to write: http://sandrotosi.me/ingress/london/tfl_bus_routes_first_stop.html (click on any marker)

**Comment by sstephans** [comment]
Yes! That looks like what I need. Thank you!

**Comment by sandrotosi** [comment]
sorry @sstephans forgot to make it explicit that PR has not been merged (not reviewed) so far

**Comment by sstephans** [comment]
Good to know. Thanks
